workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"' # Disable pipeline for Merge requests

include:
  - local: devops/vars/global.yml
  - project: 'CBEx/devops'
    stage: prebuild
    ref: test
    file: /gitlab_balckduck_scan.yml
    when: always

include:
  - project: 'CBEx/unity/Unity-QA'
    ref: Unity_QA_Testing
    file: /.gitlab-ci.yml
    when: always
    needs:
      - deployqa

stages:
  - prebuild
  #- sonar #sonar report
  #- test 
  #- blackduckscan
  - builddev
  - deploydev
  - builddev2
  - deploydev2
  - buildl4
  - deployl4
  - buildqa
  - deployqa
  - builddemo
  - deploydemo
  - builduat
  - deployuat
  - buildprod
  - deployprod
  - pafexecution_regression
  - deploystack

sonar:
  stage: prebuild
  image: sonarsource/sonar-scanner-cli:4.5
  #needs:
    #- test
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev" || $CI_COMMIT_REF_NAME =~ /^feature/ || $CI_COMMIT_REF_NAME =~ /^bugfix/
    - when: always
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: 0
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  artifacts:
    paths:
      - coverage/
  script:
    - apk upgrade --update-cache --available && apk add openssl && rm -rf /var/cache/apk/*
    - sonar-scanner -X -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.projectKey=$CI_PROJECT_NAME
  
#test:
  #stage: prebuild
  #image: node:14
  #except: 
    #- qa
    #- uat
  #script:
    #- yarn install #v1.22.5
    #- yarn run test --coverage
  #artifacts:
    #paths:
      #- coverage/
  #allow_failure: false
  #tags:
    #- docker

dev:
  stage: builddev
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  only:
    - dev
    - tags
  script:
    - cat $devaccount >> build.env
    - cat $frontendacmdev >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
  environment: dev

deploydev:
  stage: deploydev
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - dev
  only:
    - dev
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker
  environment: dev

dev2:
  stage: builddev2
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  when: manual
  only:
    #- dev
    - migration
    - tags
  script:
    - cat $devaccount > build.env #(Skip if creating env in production account)
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
  environment: dev2

deploydev2:
  stage: deploydev2
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - dev2
  only:
    #- dev
    - migration
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker
  environment: dev2

.dev3:
  stage: builddev3
  image: node:12
  when: manual
  variables:
    Environment: $CI_JOB_NAME
  only:
    - L4
  script:
    - cat $devaccount >> build.env
    - cat $frontendacmdev >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
  environment: dev3

.deploydev3:
  stage: deploydev3
  when: manual
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - dev3
  only:
    - L4
  script:    
    - source build.env  
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker
  environment: dev3

buildl4:
  stage: buildl4
  image: node:14
  when: manual
  variables:
    Environment: l4
  only:
    - dev
    - migration
    - tags
  script:
    - cat $prod_build >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
  environment: l4

deployl4:
  stage: deployl4
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - buildl4
  when: manual
  only:
    - dev
    - tags
  script:    
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker
  environment: l4

demo:
  stage: builddemo
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  when: manual
  only:
    - demonew
    - dev
    - tags
  script:
    - cat $devaccount >> build.env
    - cat $frontendacmdev >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
  environment: demo

deploydemo:
  stage: deploydemo
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - demo
  when: manual
  only:
    - demonew
    - dev
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker
  environment: demo

qa:
  stage: buildqa
  image: node:14
  needs:
    - deploydev
  when: manual
  variables:
    Environment: $CI_JOB_NAME
  only:
    - tags
  script:
    - cat $prod_build >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
  environment: qa

deployqa:
  stage: deployqa
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - qa
  when: manual
  only:
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region "us-east-1"
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region "us-east-1"
  tags:
    - docker
  environment: qa

uat:
  stage: builduat
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  needs:
  - deployqa
  when: manual
  only:
    - tags
  script:
    - cat $prod_build >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
  environment: uat

deployuat:
  stage: deployuat
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - uat
  when: manual
  only:
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region "us-east-1"
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region "us-east-1"
  tags:
    - docker
  environment: uat

prod:
  stage: buildprod
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  only:
    - tags
  needs:
    - deployuat
  when: manual
  script:
    - cat $prod_build >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
  environment: prod

deployprod:
  stage: deployprod
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - prod
  only:
    - tags
  when: manual
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region "us-east-1"
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region "us-east-1"
  tags:
    - docker
  environment: prod

pafexecution_regression:
  stage: pafexecution_regression
  needs:
    - deployqa
  #when: manual
  only:
    - tags
  variables:
    ENV_NAME: svt
  trigger:
    project: 'CBEx/unity/Unity-QA'
    branch: Unity_QA_Testing
    strategy: depend


deploystack:
  stage: deploystack
  rules:
    #- if:  $CI_COMMIT_REF_NAME =~ /^feature/ || $CI_COMMIT_REF_NAME =~ /^bugfix/
    #when: never
    #- if:  $CI_COMMIT_REF_NAME =~ /demonew/
    #when: never
    - if: '$DeployStack == "True"' #this flag drives whether to deploy the infrastructure stack
      when: always
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  #dependencies:
    #- l4
  script:
    - source build.env
    - aws cloudformation validate-template --template-body file://devops/cloudformation/cbex-unity-frontend-cf.yml --region $Region
    - aws cloudformation deploy --stack-name $Project-$Product-$Module-$Environment --template-file devops/cloudformation/cbex-unity-frontend-cf.yml --parameter-overrides $(cat devops/vars/cfparameters.ini) $(cat build.env) --tags $(cat devops/vars/cftags.ini) Environment=$Environment Lifecycle=$Environment --region $Region
