workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"' # Disable pipeline for Merge requests

include:
  - local: devops/vars/global.yml
  - project: 'CBEx/devops'
    ref: test
    file: /gitlab_balckduck_scan.yml

stages:
  - blackduckscan
  - sonar #sonar report
  #- builddev
  #- deploydev
  - builddev2
  - deploystack
  - deploydev2
  #- buildqa
  #- deployqa
  #- builddemo
  #- deploydemo
  #- builduat
  #- deployuat
  #- buildprod
  #- deployprod
  #- deploystack
  

sonar:
  stage: sonar
  image: sonarsource/sonar-scanner-cli:4.5
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev" || $CI_COMMIT_REF_NAME =~ /^feature/ || $CI_COMMIT_REF_NAME =~ /^bugfix/
    - when: always
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: 0
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - apk upgrade --update-cache --available && apk add openssl && rm -rf /var/cache/apk/*
    - sonar-scanner -X -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.projectKey=$CI_PROJECT_NAME

.dev:
  stage: builddev
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  only:
    - dev
    - migration
    - tags
  script:
    - cat $devaccount >> build.env
    - cat $frontendacmdev >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker

.deploydev:
  stage: deploydev
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - dev
  only:
    - dev
    - migration
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker
dev2:
  stage: builddev2
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  when: manual
  only:
    - dev2
  script:
    - cat $devaccount > build.env #(Skip if creating env in production account)
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker

deploydev2:
  stage: deploydev2
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - dev2
  only:
    - dev2
    #- dev
    #- tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker

dev2:
  stage: builddev2
  image: node:12
  variables:
    Environment: $CI_JOB_NAME
  only:
    - dev2
  script:
    - cat $devaccount > build.env #(Skip if creating env in production account)
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker
 
deploystack:
  stage: deploystack
  rules:
    #- if:  $CI_COMMIT_REF_NAME =~ /^feature/ || $CI_COMMIT_REF_NAME =~ /^bugfix/
      #when: never
    #- if:  $CI_COMMIT_REF_NAME =~ /demonew/
      #when: never
    - if: '$DeployStack == "True"' #this flag drives whether to deploy the infrastructure stack
      when: always
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - dev2
  script:
    - source build.env
    - aws cloudformation validate-template --template-body file://devops/cloudformation/cbex-unity-frontend-cf.yml --region $Region
    - aws cloudformation deploy --stack-name $Project-$Product-$Module-$Environment --template-file devops/cloudformation/cbex-unity-frontend-cf.yml --parameter-overrides $(cat devops/vars/cfparameters.ini) $(cat build.env) --tags $(cat devops/vars/cftags.ini) Environment=$Environment Lifecycle=$Environment --region $Region

deploydev2:
  stage: deploydev2
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - dev2
  when: manual
  only:
    - dev2
    #- dev
    #- tags
  script:    
    - source build.env  
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker

.demo:
  stage: builddemo
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  when: manual
  only:
    - demonew
    - dev
    - tags
  script:
    - cat $devaccount >> build.env
    - cat $frontendacmdev >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker

.deploydemo:
  stage: deploydemo
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - demo
  when: manual
  only:
    - demonew
    - dev
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker

.qa:
  stage: buildqa
  image: node:14
  needs:
    - deploydev
  when: manual
  variables:
    Environment: $CI_JOB_NAME
  only:
    - tags
  script:
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker

.deployqa:
  stage: deployqa
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - qa
  when: manual
  only:
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker

.uat:
  stage: builduat
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  #needs:
  #- deployqa
  when: manual
  only:
    - tags
  script:
    - cat $prod_build >> build.env
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker

.deployuat:
  stage: deployuat
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - uat
  #when: manual
  only:
    - tags
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region $Region
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region $Region
  tags:
    - docker

.prod:
  stage: buildprod
  image: node:14
  variables:
    Environment: $CI_JOB_NAME
  only:
    - tags
  needs:
    - deployuat
  when: manual
  script:
    - cat devops/vars/${Environment}.env >> build.env
    - source build.env
    - yarn cache clean
    - yarn install
    - yarn build:$Environment
  artifacts:
    paths:
      - dist/
      - build.env
  tags:
    - docker

.deployprod:
  stage: deployprod
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - prod
  only:
    - tags
  when: manual
  script:
    - source build.env
    - aws s3 sync dist/ s3://$BucketName/ --delete --region "us-east-1"
    - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?starts_with(AliasICPRecordals[0].CNAME, '$Route53Cname')].Id" --output text) --paths "/*" --region "us-east-1"
  tags:
    - docker

.deploystack:
  stage: deploystack
  rules:
    #- if:  $CI_COMMIT_REF_NAME =~ /^feature/ || $CI_COMMIT_REF_NAME =~ /^bugfix/
    #when: never
    #- if:  $CI_COMMIT_REF_NAME =~ /demonew/
    #when: never
    - if: '$DeployStack == "True"' #this flag drives whether to deploy the infrastructure stack
      when: always
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - demo
  script:
    - source build.env
    - aws cloudformation validate-template --template-body file://devops/cloudformation/cbex-unity-frontend-cf.yml --region $Region
    - aws cloudformation deploy --stack-name $Project-$Product-$Module-$Environment --template-file devops/cloudformation/cbex-unity-frontend-cf.yml --parameter-overrides $(cat devops/vars/cfparameters.ini) $(cat build.env) --tags $(cat devops/vars/cftags.ini) Environment=$Environment Lifecycle=$Environment --region $Region
