# Project settings.
sonar.projectKey=unity-app-frontend
sonar.projectName=unity-app-frontend
sonar.projectDescription=unity-app-frontend
sonar.links.ci=https://gitlabrnds.quintiles.com/cbex/unity/unity-app-frontend/-/pipelines


# Scan settings.
sonar.projectBaseDir=.
# Define the directories that should be scanned. Comma separated.
sonar.sources=.

# Fail CI pipeline if Sonar fails.
sonar.qualitygate.wait=false
sonar.qualitygate.timeout=300

#Coverage Report
sonar.exclusions=**/*.test.ts,src/components/screens/Approvals/__test__/index.test.js,src/components/views/modals/__test__/AnswerHistory.test.js,src/components/screens/Approvals/__test__/Approvals.test.jsx,src/context/__tests__/SocketContext.test.jsx,src/components/screens/Approvals/__test__/utils.test.js,src/components/screens/Proposal/__tests__/Sidebar.test.js,src/components/screens/Approvals/__test__/Section.test.jsx,src/components/common/__tests__/CollapsibleList.test.js,src/components/screens/Approvals/__tests__/ActionButtons.test.js,src/components/views/toolbar/__test__/index.test.js
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.coverage.exclusions=**/__tests__/**,**/__test__/**,src/constants/**
sonar.javascript.coveragePlugin=lcov
#sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
