# Project settings.
sonar.projectKey=unity-app-frontend
sonar.projectName=unity-app-frontend
sonar.projectDescription=unity-app-frontend
sonar.links.ci=https://gitlabrnds.quintiles.com/cbex/unity/unity-app-frontend/-/pipelines


# Scan settings.
sonar.projectBaseDir=.
# Define the directories that should be scanned. Comma separated.
sonar.sources=.

# Fail CI pipeline if Sonar fails.
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300 # seconds

#Coverage Report
sonar.exclusions=**/*.test.ts
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.javascript.coveragePlugin=lcov
#sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
