// flow-typed signature: e96cd53c7cd8462b3dcd2fcae66a621e
// flow-typed version: <<STUB>>/and_v^0.0.3/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'and'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'and' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'and/and' {
  declare module.exports: any;
}

declare module 'and/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'and/and.js' {
  declare module.exports: $Exports<'and/and'>;
}
declare module 'and/tests.js' {
  declare module.exports: $Exports<'and/tests'>;
}
