export default [
  {
    'Proposal Team-P0X': 'Business Developer Team',
    'Proposal Team-D6B': 'TSL Team',
    'Proposal Team-P0C': 'Medic Team',
    'Proposal Team-A2W': 'Project Lead Team',
    'Proposal Team-Z5P': 'Proposal Developer Team',
    'Proposal Team-O0Z': 'Analytics Strategy Lead Team',
    'Proposal Team-L6S': 'Clinical DS&B Team',
    'Country Strategy-N9P': 'Target Countries',
    'Win Strategy-J5S': 'Study Outcome Success',
    'Win Strategy-AB9': 'Historic strategy impact',
    'Win Strategy-U9B': 'Customer Need and Selection Criteria',
    'Pricing-W9S': 'Price Point',
    'Study Challenges-G0H': 'Medical Challenges',
    'Site Strategy-D0S': 'Patient Pathway',
    'Opportunity Overview-N0J': 'Study Design',
    'Win Strategy-AR2': 'IQVIA Position',
    'Team structure & location-C0X': 'Team Member Location',
    'Proposal Team-D8U': 'Feasibility Lead',
    'Proposal Team-I9S': 'Regulatory & Start-Up Lead',
    'Opportunity Overview-Z7C': 'CRM Number',
    'Opportunity Overview-T1U': 'Proposal Due Date',
    'Opportunity Overview-M9D': 'Customers Full Name',
    'Opportunity Overview-I7N': 'Therapeutic Area',
    '8959b856-0f49-4c4e-8ec8-f5955320866a': 'Indication',
    'Opportunity Overview-D3B': 'Study Phase',
    '7ba722f4-8822-4e64-8086-acc8dbc746ab':
      'Is this a full or partial virtual trial?',
    '5c2af12a-f1ff-41a9-bd74-fe2ae340faff': 'Study Start Date',
    'Opportunity Overview-Z1V': 'Study Compound',
    'Country Strategy-H7V': 'Country Strategy-H7V',
    '6bdaa786-a85a-454e-add6-f930ef3ec88a': 'Customers Primary Hot Button',
    'Proposal Team-L8N': 'Project Leadership, Director'
  }
];
