#Prod
#EnableVersioning=Enabled
#AcmCertificateArn=arn:aws:acm:us-east-1:822747920909:certificate/31d24e42-9aee-4a97-ab01-500edeba6875

#Dev
EnableVersioning=Enabled
AcmCertificateArn=arn:aws:acm:us-east-1:407156019863:certificate/e0fc1d86-330e-4e34-90e6-a115dbdf1196 